### PR TITLE
Some suggested features

### PR DESCRIPTION
**Pull request by Misaka13514**
If you don't like one of my commits, just cherry pick other commit(s).

- paste file from the web page
- validate form on the web
- remove some default chars for human readability (`oO0LlI19gqVvUu` and `+-=@`)
- add button to return to the web index page

### CODE REVIEW

**Comment by Misaka13514** [comment]
merge conflict fixed

**Comment by Misaka13514** [comment]
Maybe css can be modified to add dark mode and mobile layout. (

**Comment by SharzyL** [comment]
Yes, mobile layout is an annoying issue...

**Comment by SharzyL** [comment]
Making changes on the current handwritten HTML and borrowed CSS is painful, I am considering rewriting it in a standalone HTML file, upload the HTML to the pastebin and redirect index page to that pastebin content.

**Pull request merged**
