### PR TITLE
WIP: add copy button

### PR DESCRIPTION
**Pull request by Misaka13514**
Trying to re-add the copy button...... need some help on css(

It will be good if a copy prompt displayed after clicking the button(?) for example, change `Copy` to `Copied`.

It's a bit difficult for my ability ... and I'm not so efficient, sorry for just an unfinished draft pull request.

### CODE REVIEW

**Comment by Misaka13514** [comment]
Should I format the code of `static/index.html`? I don't know the indentation.

**Comment by SharzyL** [comment]
Currently HTML and CSS is indented with 4 spaces and JS is indented with 2 spaces. Please keep this for now (maybe I will unify the indentations later).

**Comment by SharzyL** [comment]
Tip: In a recent commit (89874bb058651477e1d0688cbaabb6cd793de639) we started separating HTML, CSS and JS in different files. It might make your development easier.

**Comment by Misaka13514** [comment]
Thank you! My css is very poor, can you help me (o´･_･)っ

**Comment by Misaka13514** [comment]
According to the original design, the input box occupies the full width, and I need to make it share the full width with the button. My only way at present is to set the `width` to `calc(...)`.

**Comment by SharzyL** [comment]
Try flexbox ([here](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) is a guide)

**Comment by Misaka13514** [comment]
Looks better now.  But the textContent of button can't change back at present.🤦🏻 (e.g. submit another paste)

**Comment by SharzyL** [comment]
implemented in 25063683c20dda77b2168c7352af78fd29d2a9ef

**Pull request closed without merging**
